wandb_version: 1

BATCH_SIZE:
  desc: null
  value: 16
INPUT_SIZE:
  desc: null
  value:
  - 448
  - 448
LR:
  desc: null
  value: 0.001
PROPOSAL_NUM:
  desc: null
  value: 6
SAVE_FREQ:
  desc: null
  value: 1
WD:
  desc: null
  value: 0.0001
_wandb:
  desc: null
  value:
    cli_version: 0.12.7
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.13
    start_time: 1637565590
    t:
      1:
      - 1
      3:
      - 16
      4: 3.6.13
      5: 0.12.7
      8:
      - 3
      - 5
resume:
  desc: null
  value: ''
save_dir:
  desc: null
  value: train_log/models/
